name: libogc-mod build

on: [push, pull_request]

jobs:
  build:
    name: Build libogc-mod
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout libogc-mod
      uses: actions/checkout@v2

    - name: Build libogc-mod
      run: make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libogc-mod
        path: /opt/devkitpro/libogc-mod
